WordPress
cloudimix/wordpress_mysql_kubespray_oracle_cloud pull request #1
Opened 2022-08-16 16:30 UTC by cloudimix

2022-09-01 06:23 UTC, delfer requested changes

2022-09-01 06:23 UTC, delfer commented on Makefile
> +	ansible-playbook -i dynamic_inventory.py kubectl_localhost.yml --ask-become-pass
в этом файле весь код оптимизирован на отсутствие ручного ввода (-auto-approve), но тут ты делаешь наоборот --ask-become-pass, лучше все привести к одному виду. Плюс я думаю kubectl_localhost не должен требовать прав рута для выполнения

2022-09-01 06:23 UTC, delfer commented on myfiles/volumes_mount.yml
> +        - "{{ mounts }}"
теоретически создавать папку необязательно. Из описания ansible.posix.mount:
If mounted, the device will be actively mounted and appropriately configured in fstab. If the mount point is not present, the mount point will be created.

2022-09-01 06:23 UTC, delfer commented on myfiles/group_vars/all
> +app_main_url: https://raw.githubusercontent.com/cloudimix/myfiles/main/wordpress_deployment_files/
может лучше эти файлы брать из первоисточника или на крайний случай сюда переложить?

2022-09-02 10:44 UTC, cloudimix commented on Makefile
> +	ansible-playbook -i dynamic_inventory.py kubectl_localhost.yml --ask-become-pass
/etc/sudoers
%sudo ALL=(ALL:ALL) NOPASSWD: ALL
Теперь норм

2022-10-03 11:50 UTC, merged